### ISSUE TITLE
is it ready to be version 1, now?

### ISSUE THREAD

**Issue by hadihammurabi** [ngamux/ngamux#6]
I need to communicate with all public users, testers, and contributors about version tagging of this HTTP router.
**is it ready to be version 1, now?**

let me mention all contributors:
@born2ngopi @ClavinJune @milhamsuryapratama

**Comment by ClavinJune** [comment]
I don't think so, the codes on `group.go` is not dry enough.

I think it should be refactored first before we tag it as V1, otherwise, when we refactor it later, it won't be backward compatible and the major version will be updated. Let's make sure that the code doesn't need to be changed in the near future

**Comment by hadihammurabi** [comment]
> I don't think so, the codes on `group.go` is not dry enough.
> 
> I think it should be refactored first before we tag it as V1, otherwise, when we refactor it later, it won't be backward compatible and the major version will be updated. Let's make sure that the code doesn't need to be changed in the near future

Alright. I agree about fixing the code first.
But, can you explain about `group.go is not dry enough`?
What does it mean?

**Comment by ClavinJune** [comment]
as You see, both the `group.go` and the `ngamux.go` have the same Get, Post, etc func, it could be dried, instead of creating the same function for the same functionality

**Comment by hadihammurabi** [comment]
> as You see, both the `group.go` and the `ngamux.go` have the same Get, Post, etc func, it could be dried, instead of creating the same function for the same functionality

Alright. Let's see, how we can do it better.
Thanks for your point of view.

**Comment by ClavinJune** [comment]
btw, I found a way to remove the `group.go` while retaining the functionality, I could create a PR after #7 is merged

**Comment by hadihammurabi** [comment]
> btw, I found a way to remove the `group.go` while retaining the functionality, I could create a PR after #7 is merged

I will merge any changes into other branch.
To make more clean transition if we want to tag to v1.

**Comment by ClavinJune** [comment]
#8 would be enough to dry up the duplicated code, I use Laravel style grouping

And you might want to change your middleware implementation because you're applying the middleware whenever the request is handled, it might not be a good move because it adds more latencies on every requests, u can change the implementation like my Usage Example in #8

**Comment by hadihammurabi** [comment]
Great. I appreciate your contributions and thank you once again.
Really happy about that.

Let's discuss about #8 in PR review page.

**Comment by hadihammurabi** [comment]
It was [released](https://github.com/ngamux/ngamux/releases/tag/v1.0.0)
